title: ContosoAir Docs
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
baseurl: "/ContosoAir-Docs"
description: "ContosoAir Docs offers helpful, easy-to-follow travel booking guides, pricing information, and support resources."